apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "name" . }}
          servicePort: {{ .Values.service.externalPort }}
